---
categories:
  услуга, работа:
    - другое
  спорт:
    - другое
  одежда:
    - другое
  электроника:
    - другое
  транспорт:
    - другое
  украшения:
    - другое
  красота, уход:
    - другое
  досуг, книги:
    - книги
    - настолки
    - мячи
    - спорт
    - другое
  для дома:
    - бытовая техника
    - уборка, клининг
    - удленители, переходники # nuduck
    - lan, usb, провода # nuduck
    - сушилки # nuduck
    - чайники
    - другое
  канцтовары:
    - другое
  подарки:
    - другое
  аптека:
    - Презервативы # sexify
    - Смазки # sexify
    - другое
  даром:
    - другое
  фастфуд:
    - Донеры
    - Боулы
    - другое
  напитки:
    - энергетики # boost_energy
    - чаи # boost_energy
    - соки # boost_energy
    - кола # boost_energy
  еда:
    - рамен # sexify
    - сладкое # sexify
    - сендвичи # sexify
    - дошик # sexify
    - чипсы/кириешки # sexify
    - морепродукты # sexify
    - другое