---
categories:
  Услуга, Работа:
    - Другое
  Спорт:
    - Другое
  Одежда:
    - Другое
  Электроника:
    - Другое
  Транспорт:
    - Другое
  Украшения:
    - Другое
  Красота, Уход:
    - Другое
  Досуг, Книги:
    - Книги
    - Дормгеймс
    - Другое
  Для Дома:
    - Бытовая техника
    - Уборка, клининг
    - Удленители, Переходники # nuduck
    - LAN, USB, провода # nuduck
    - Сушилки # nuduck
    - Чайники
    - Другое
  Канцтовары:
    - Другое
  Подарки:
    - Другое
  Аптека:
    - Презервативы # sexify
    - Смазки # sexify
    - Другое
  Даром:
    - Другое
  Фастфуд:
    - Донеры
    - Боулы
    - Рамен # sexify
    - Другое
  Напитки:
    - Энергетики # boost_energy
    - Чаи # boost_energy
    - Соки # boost_energy
    - Кола # boost_energy
  Другие Продукты:
    - Морепродукты # sexify
    - Другое
  # 21+ Алко:
  #   - Другое
  # 21+ Сиги: # nuduck
  #   - Однаразки
  #   - Стики # sexify
  #   - Сигареты
  #   - Табак
  #   - айкосы
  #   - Гло
  #   - Другое